name: newsforge

services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: nf
      POSTGRES_PASSWORD: nf
      POSTGRES_DB: newsforge
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nf -d newsforge"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7.2-alpine
    ports: ["6379:6379"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["api"]
    environment:
      DJANGO_SETTINGS_MODULE: newsforge.settings.dev
      DATABASE_URL: postgres://nf:nf@db:5432/newsforge
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["worker"]
    environment:
      DJANGO_SETTINGS_MODULE: newsforge.settings.dev
      DATABASE_URL: postgres://nf:nf@db:5432/newsforge
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["beat"]
    environment:
      DJANGO_SETTINGS_MODULE: newsforge.settings.dev
      DATABASE_URL: postgres://nf:nf@db:5432/newsforge
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  db_data:
